<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNjbrgqj\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNjbrgqj/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerNjbrgqj.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerNjbrgqj\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerNjbrgqj\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Njbrgqj',
    'container.build_id' => '8b73ebaa',
    'container.build_time' => 1543297113,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerNjbrgqj');
