<?php

namespace EShopBundle\Repository;

/**
 * ProductCartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductCartRepository extends \Doctrine\ORM\EntityRepository
{
}
